# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cebdaec1a71a1eb48dac0969394fb0f9961ebe8f6a9dfcecb60dad73c7c07980ed9243c11853990871bc76f0b5289bcab19510eb0b0a5d60a5e6bfc10dd948bd

test:
  secret_key_base: 45d571d16ae551e961f64a1328de735eae95a4a0ba05d029389dfbb8a79d9e38f3bef332fa5394a47bf060a6f0dddca616b312a869f77280061f3e7d67eb2e17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
